# Define the stages
stages:
  - test

# Job to run the Python script
run_python_script:
  stage: test
  image: python:3.9  # Use the official Python Docker image
  script:
    - pip install -r requirements.txt  # Install dependencies (if you have a requirements.txt file)
    - python script.py  # Run your Python script
