stages:
  - vault_login
  - run_script

variables:
  # Vault server URL and authentication details (should be set as CI/CD variables in GitLab)
  VAULT_SERVER_URL: "http://127.0.0.1:8200"  # Replace with your actual Vault server URL
  VAULT_AUTH_ROLE: "your-role"               # Replace with your Vault authentication role
  VAULT_ID_TOKEN: "your-jwt-token"           # Replace with your JWT token (or use GitLab CI/CD variable)

vault_login:
  stage: vault_login
  image: hashicorp/vault:latest
  script:
    - echo "Logging into Vault using JWT..."
    - export VAULT_ADDR=$VAULT_SERVER_URL  # Set the Vault server URL
    - export VAULT_TOKEN=$(vault write --field=token auth/jwt/login role=$VAULT_AUTH_ROLE jwt=$VAULT_ID_TOKEN)
    - echo "Vault login successful. Token obtained."

run_script:
  stage: run_script
  image: python:3.9-slim
  before_script:
    - pip install hvac
  script:
    - echo "Running Python script with Vault token..."
    - export VAULT_ADDR=$VAULT_SERVER_URL  # Set the Vault server URL again if needed
    - export VAULT_TOKEN=$VAULT_TOKEN  # Ensure the token is available as an environment variable
    - python my_script.py  # Replace 'my_script.py' with your actual script name

  # Optional: specify the files or directories to be saved as artifacts
  artifacts:
    paths:
      - group_policies.csv
